name: Azure Deploy
on: [push]
jobs:
  azure-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: List Resource Groups
        run: |
          az group list -o table
      - name: Azure Logout
        run: |
          az logout
          az cache purge
          az account clear